[config]
default_to_workspace = false

[env]
# Determines the version of Elasticsearch docker container used
STACK_VERSION = "8.0.0-SNAPSHOT"
# Determines the distribution of docker container used. Either xpack or oss
TEST_SUITE = "xpack"
# Set publish flags to dry-run by default, to force user to explicitly define for publishing
CARGO_MAKE_CARGO_PUBLISH_FLAGS = "--dry-run"

[tasks.set-oss-env]
category = "Elasticsearch"
description = "Sets ELASTICSEARCH_URL environment variable if not already set for later tasks when oss test suite used"
private = true
condition = { env = { "TEST_SUITE" = "oss" }, env_not_set = ["ELASTICSEARCH_URL"] }
env = { "ELASTICSEARCH_URL" = "http://localhost:9200" }

[tasks.set-xpack-env]
category = "Elasticsearch"
description = "Sets ELASTICSEARCH_URL environment variable if not already set for later tasks when xpack test suite used"
private = true
condition = { env = { "TEST_SUITE" = "xpack" }, env_not_set = ["ELASTICSEARCH_URL"] }
env = { "ELASTICSEARCH_URL" = "https://elastic:changeme@localhost:9200" }

[tasks.set-elasticsearch-crate-env]
category = "Elasticsearch"
description = "Sets CARGO_MAKE_WORKING_DIRECTORY environment variable to elasticsearch crate"
private = true
env = { "CARGO_MAKE_WORKING_DIRECTORY" = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/elasticsearch" }

[tasks.run-yaml-test-runner]
category = "Elasticsearch"
description = '''
Runs yaml_test_runner package to generate tests from yaml files for a given Elasticsearch commit.
The commit to use is retrieved from the running Elasticsearch instance
'''
private = true
script = ["cargo run -p yaml_test_runner -- -u ${ELASTICSEARCH_URL}"]
dependencies = ["start-elasticsearch"]

[tasks.run-yaml-test-runner.windows]
script = ["cargo run -p yaml_test_runner -- -u %ELASTICSEARCH_URL%"]

[tasks.test-yaml-test-runner]
category = "Elasticsearch"
private = true
condition = { env_set = [ "ELASTICSEARCH_URL" ], env_not_set = ["CI"] }
command = "cargo"
args = ["test", "-p", "yaml_test_runner", "--", "--test-threads=1"]
dependencies = ["generate-yaml-tests"]

[tasks.test-yaml-test-runner-ci]
category = "Elasticsearch"
private = true
condition = { env_set = [ "ELASTICSEARCH_URL", "CI" ] }
script = ["cargo test -p yaml_test_runner -- --test-threads=1 -Z unstable-options --format json | tee test_results/results.json"]
dependencies = ["generate-yaml-tests"]

[tasks.test-elasticsearch]
category = "Elasticsearch"
private = true
condition = { env_set = [ "ELASTICSEARCH_URL" ], env = { "TEST_SUITE" = "xpack" } }
command = "cargo"
args = ["test", "-p", "elasticsearch"]
dependencies = ["start-elasticsearch"]

[tasks.run-api-generator]
category = "Elasticsearch"
private = true
command = "cargo"
args = ["run", "-p", "api_generator"]

[tasks.create-test-results-dir]
category = "Elasticsearch"
private = true
condition = { env_set = [ "CI" ] }
script = ["[ -d test_results ] || mkdir -p test_results"]

[tasks.install-cargo2junit]
category = "Elasticsearch"
private = true
script = ["cargo install cargo2junit"]

[tasks.convert-test-results-junit]
category = "Elasticsearch"
private = true
condition = { env_set = [ "CI" ] }
script = ["cat test_results/results.json | cargo2junit > test_results/cargo-junit.xml"]
dependencies = ["install-cargo2junit"]

[tasks.publish-impl]
description = "Runs the cargo publish command."
category = "Elasticsearch"
private = true
script_runner = "@shell"
script = [
"""
pushd elasticsearch
cargo publish ${CARGO_MAKE_CARGO_PUBLISH_FLAGS}
popd
"""
]

# ============
# Public tasks
# ============

[tasks.start-elasticsearch]
category = "Elasticsearch"
description = "Starts Elasticsearch docker container with the given version and distribution"
condition = { env_set = [ "STACK_VERSION", "TEST_SUITE" ], env_not_set = ["CI"] }
script = ["DETACH=true bash .ci/run-elasticsearch.sh"]
dependencies = ["set-oss-env", "set-xpack-env"]

[tasks.start-elasticsearch.windows]
script = ["bash -c \"STACK_VERSION=%STACK_VERSION% TEST_SUITE=%TEST_SUITE% DETACH=true bash .ci/run-elasticsearch.sh\""]

[tasks.stop-elasticsearch]
category = "Elasticsearch"
description = "Stops Elasticsearch docker container, if running"
condition = { env_set = [ "STACK_VERSION", "TEST_SUITE" ], env_not_set = ["CI"] }
script = ["CLEANUP=true bash .ci/run-elasticsearch.sh"]
dependencies = ["set-oss-env", "set-xpack-env"]

[tasks.stop-elasticsearch.windows]
script = ["bash -c \"STACK_VERSION=%STACK_VERSION% TEST_SUITE=%TEST_SUITE% CLEANUP=true bash .ci/run-elasticsearch.sh\""]

[tasks.test-yaml]
category = "Elasticsearch"
description = "Generates and runs yaml_test_runner package xpack/oss tests against a given Elasticsearch version"
condition = { env_set = [ "STACK_VERSION", "TEST_SUITE" ] }
dependencies = ["generate-yaml-tests", "create-test-results-dir", "test-yaml-test-runner", "test-yaml-test-runner-ci", "convert-test-results-junit"]
run_task = "stop-elasticsearch"

[tasks.test-generator]
category = "Elasticsearch"
clear = true
description = "Runs api_generator tests"
command = "cargo"
args = ["test", "-p", "api_generator"]

[tasks.test]
category = "Elasticsearch"
clear = true
description = "Runs elasticsearch package tests against a given Elasticsearch version"
env = { "TEST_SUITE" = { value = "xpack", condition = { env_set = ["TEST_SUITE"] } } }
dependencies = ["test-elasticsearch"]
run_task = "stop-elasticsearch"

[tasks.generate-yaml-tests]
category = "Elasticsearch"
description = "Generates Elasticsearch client tests from YAML tests"
dependencies = ["run-yaml-test-runner"]
run_task = "format"

[tasks.generate-api]
category = "Elasticsearch"
description = "Generates Elasticsearch client from REST API specs"
dependencies = ["run-api-generator"]
run_task = "format"

[tasks.docs]
description = "Generate Elasticsearch client documentation and opens in browser"
clear = true
category = "Elasticsearch"
command = "cargo"
args = ["doc", "-p", "elasticsearch", "--no-deps", "--open"]

[tasks.generate-release-notes]
category = "Elasticsearch"
description = "Generates release notes for Elasticsearch client"
# assumes clients-team repo is checked out as a sibling of elasticsearch-rs
condition = { env_set = ["OLD_VERSION", "NEW_VERSION"], files_exist = [ "${CARGO_MAKE_WORKING_DIRECTORY}/../clients-team/scripts/release-notes-generator/Dockerfile" ] }
script_runner = "bash"
script = [
"""
pushd ./../clients-team/scripts/release-notes-generator
docker build --file ./Dockerfile --tag clients-team/release_notes_generator .
popd
docker run -v "${CARGO_MAKE_WORKING_DIRECTORY}/.ci/release/config.yml:/usr/src/release_notes_generator/config.yml" --rm clients-team/release_notes_generator -o ${OLD_VERSION} -n ${NEW_VERSION}
"""
]

[tasks.generate-release-notes.windows]
script_runner = "cmd"
script = [
"""
rem pushd needs backslash directory separators...
pushd .\\..\\clients-team\\scripts\\release-notes-generator
docker build --file ./Dockerfile --tag clients-team/release_notes_generator .
popd
docker run -v "%CARGO_MAKE_WORKING_DIRECTORY%/.ci/release/config.yml:/usr/src/release_notes_generator/config.yml" --rm clients-team/release_notes_generator -o %OLD_VERSION% -n %NEW_VERSION%
"""
]

[tasks.publish]
clear = true
dependencies = [ "publish-impl" ]
run_task = "generate-release-notes"

[tasks.package]
clear = true
description = "Runs the cargo package command for elasticsearch crate."
category = "Elasticsearch"
script_runner = "@shell"
script = [
"""
pushd elasticsearch
cargo package ${CARGO_MAKE_CARGO_PACKAGE_FLAGS}
popd
"""
]

[tasks.default]
clear = true
script = ['''
    echo
    echo "Main tasks:"
    echo "- generate-api: Generates Elasticsearch client from REST API specs"
    echo "- start-elasticsearch: Starts Elasticsearch docker container with the given version and distribution"
    echo "- stop-elasticsearch: Stops Elasticsearch docker container, if running"
    echo
    echo "- test-yaml: Generates and runs yaml_test_runner package xpack/oss tests against a given Elasticsearch version"
    echo "- test-generator: Generates and runs api_generator package tests"
    echo "- test: Runs elasticsearch package tests against a given Elasticsearch version"
    echo
    echo "- generate-release-notes: Generates release notes for elasticsearch crate, with OLD_VERSION and NEW_VERSION matching release version GitHub labels e.g. v7.9.0-alpha.1"
    echo "- package: Packages the elasticsearch crate. package flags can be overridden with CARGO_MAKE_CARGO_PACKAGE_FLAGS environment variable"
    echo "- publish: Publishes the elasticsearch crate. By default, peforms a dry run by passing --dry-run, but publish flags can be overridden with CARGO_MAKE_CARGO_PUBLISH_FLAGS environment variable"
    echo
    echo "Most tasks use these environment variables:"
    echo "- STACK_VERSION (default '$STACK_VERSION'): the version of Elasticsearch"
    echo "- TEST_SUITE ('oss' or 'xpack', default '$TEST_SUITE'): the distribution of Elasticsearch"
    echo "- CI (default not set): set when running on CI to determine whether to start Elasticsearch and format test output as JSON"
    echo
    echo "Run 'cargo make --list-all-steps' for a complete list of available tasks."
    echo
''']

[tasks.default.windows]
script = ['''
    @echo off
    echo.
    echo Main tasks:
    echo - generate-api: Generates Elasticsearch client from REST API specs
    echo - start-elasticsearch: Starts Elasticsearch docker container with the given version and distribution
    echo - stop-elasticsearch: Stops Elasticsearch docker container, if running
    echo - test-yaml: Generates and runs yaml_test_runner package xpack/oss tests against a given Elasticsearch version
    echo - test-generator: Generates and runs api_generator package tests
    echo - test: Runs elasticsearch package tests against a given Elasticsearch version
    echo.
    echo - generate-release-notes: Generates release notes for elasticsearch crate, with OLD_VERSION and NEW_VERSION matching release version GitHub labels e.g. v7.9.0-alpha.1
    echo .
    echo Most tasks use these environment variables:
    echo - STACK_VERSION (default '%STACK_VERSION%'): the version of Elasticsearch
    echo - TEST_SUITE ('oss' or 'xpack', default '%TEST_SUITE%'): the distribution of Elasticsearch
    echo - CI (default not set): set when running on CI to determine whether to start Elasticsearch and format test output as JSON
    echo.
    echo Run 'cargo make --list-all-steps' for a complete list of available tasks.
    echo.
''']